apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: identidock-requester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identidock-requester
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: identidock-requester
    spec:
      containers:
      - env:
        - name: PICTO_SERVER_IP_ADDRESS
          value: picto-svc.webapps.svc.cluster.local
        image: devopstaskacr1/request_app:0.1.1-RC.22
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /?email=test
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
        name: identidock-requester
        ports:
        - containerPort: 80
          name: identirqst-http
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /?email=test
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 140m
            memory: 100Mi
          requests:
            cpu: 70m
            memory: 50Mi
      imagePullSecrets:
      - name: webapps-reg-secret
      restartPolicy: Always
