apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: identidock-cacher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identidock-cacher
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: identidock-cacher
    spec:
      containers:
      - env:
        - name: MONGO_DB_IP_ADDRESS
          value: mongodb-svc.webapps.svc.cluster.local
        image: devopstaskacr1/cache_app:0.1.1-RC.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /isup
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        name: identidock-cacher
        ports:
        - containerPort: 80
          name: cachingport
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /isup
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 140m
            memory: 100Mi
          requests:
            cpu: 70m
            memory: 50Mi
      imagePullSecrets:
      - name: webapps-reg-secret
      restartPolicy: Always
