apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: identidock-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identidock-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: identidock-ui
    spec:
      containers:
      - env:
        - name: CACHING_SERVER_IP_ADDRESS
          value: caching-svc.webapps.svc.cluster.local
        - name: PING_IP_ADDRESS
          value: pingserver-svc.webapps.svc.cluster.local
        image: devopstaskacr1/frontend_app:0.0.1-RC.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /registration
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
        name: identidock-ui
        ports:
        - containerPort: 80
          name: identiui-http
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /registration
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 140m
            memory: 150Mi
          requests:
            cpu: 70m
            memory: 100Mi
      imagePullSecrets:
      - name: webapps-reg-secret
      restartPolicy: Always
