apiVersion: apps/v1
kind: Deployment
metadata:
  name: identidock-requester
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identidock-requester
  strategy:
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "0%"
  template:
    metadata:
      labels:
        app: identidock-requester
    spec:
      imagePullSecrets:
        - name: webapps-reg-secret
      containers:
        - name: identidock-requester
          image: 
          ports:
            - name: identirqst-http
              containerPort: 80
          env:
            - name: PICTO_SERVER_IP_ADDRESS
              value: picto-svc.webapps.svc.cluster.local
          readinessProbe:
            httpGet:
              port: 80
              path: /?email=test
            successThreshold: 1
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              port: 80
              path: /?email=test
            successThreshold: 1
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "70m"
              memory: "50Mi"
            limits:
              cpu: "140m"
              memory: "100Mi"
      restartPolicy: Always
