apiVersion: v1
kind: Service
metadata:
  name: caching-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: cachingport
      protocol: "TCP"
  selector:
    app: identidock-cacher
